image:
  file: .gitpod.Dockerfile

tasks:
  - name: Build and Run
    init: quarkus build
    command: quarkus dev

  - name: Shoot
    command: gp preview --external https://localhost:3030/

ports:
  - port: 3030
    visibility: public
    onOpen: ignore
  - port: 5005
    visibility: public
    onOpen: ignore
