image:
  file: .gitpod.Dockerfile

tasks:
  - name: Hello
    init: quarkus build
    command: echo "Welcome! 🦆"

ports:
  - port: 3030
    visibility: public
    onOpen: ignore
  - port: 5005
    visibility: public
    onOpen: ignore
