# docker run -it --rm -p 0.0.0.0:3030:3030 caravanacloud/sitting-ducks:1.0.0 
#? oc adm policy add-scc-to-group privileged system:authenticated
# oc apply -f sitting-ducks.k8s.yaml
# oc get all
# oc get route -o json | jq -r  '.items[0].status.ingress[0].host'

apiVersion: apps/v1
kind: Deployment
metadata:
    name: sitting-ducks
    labels:
        app: sitting-ducks
spec:
    replicas: 1
    selector:
        matchLabels:
            app: sitting-ducks
    template:
        metadata:
            labels:
                app: sitting-ducks
        spec:
            containers:
            - name: sitting-ducks
              image: caravanacloud/sitting-ducks:1.0.0
              
              securityContext:
                runAsUser: 1000
                runAsNonRoot: true
                allowPrivilegeEscalation: false
                capabilities:
                  drop: ["ALL"]
                seccompProfile:
                  type: "RuntimeDefault"
              ports:
              - containerPort: 3030
---
apiVersion: v1
kind: Service
metadata: 
    name: sitting-ducks-service
    labels:
        app: sitting-ducks
spec:
    selector:
        app: sitting-ducks
    type: LoadBalancer
    ports:
        - protocol: TCP
          port: 3030
          targetPort: 3030 
          nodePort: 32333
---
apiVersion: route.openshift.io/v1
kind: Route
metadata:
  name: sitting-ducks-route
spec:
  to:
    kind: Service
    name: sitting-ducks-service